name: Lesson_2

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - run: setup makefile

      - run: lint makefile

      - run: test makefile